name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://raw.githubusercontent.com/xuhao4824/feevcpcsc1/main/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1mq1jkAJia9DSoMdPiNegFAsSSp_77EVDoyMLuL3tuLeiwmDk
        USER_PASS: xinnian2021
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 10h
